config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true

complexity:
  LongMethod:
    allowedLines: 100
  LongParameterList:
    allowedConstructorParameters: 10
    allowedFunctionParameters: 8
  TooManyFunctions:
    allowedFunctionsPerClass: 15
    allowedFunctionsPerInterface: 15

exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 6

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
